### ISSUE TITLE
设备断开后调用api依然可以获取remote port

### ISSUE THREAD

**Issue by ferstar** [KunTengRom/xfrps#4]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.11.0

**What operating system and processor architecture are you using (`go env`)?**
ubuntu 16.04 amd64

**Configures you used:**
default frps_full.ini

**Steps to reproduce the issue:**
1. 断开xfrpc使设备离线
2. 调用/api/port/tcp/getport/(离线设备:runid)
3. 依然可以拿到remote port

**Describe the results you received:**
{"code":0,"msg":"","port":27864}

**Describe the results you expected:**
设备离线后应该是拿不到remote port的

**Comment by liudf0716** [comment]
thanks!
can u provide pr to fix this bug?
cause I am really very very busy for other project.

**Comment by ferstar** [comment]
@liudf0716 
我是go/js渣，有心无力，目前只整了个曲线救国的方案
见blog：https://blog.ferstar.org/post/check-online-clients-port-on-xfrps/
